'use strict';
const KEY='hanashi-notes-v1';
const $=id=>document.getElementById(id);
let notes=[],editing=null,opened=null;
const el=(tag,cls,text)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x};
async function api(path,options={}){const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await res.json();if(!res.ok)throw Error(data.error||'通信エラー');return data}
function reset(){editing=null;$('form').reset();$('formTitle').textContent='新しいネタを書く';$('cancel').hidden=true}
function render(){
 const cats=[...new Set(notes.map(n=>n.category||'未分類'))].sort((a,b)=>a.localeCompare(b,'ja')),current=$('filter').value;
 $('filter').replaceChildren(new Option('すべてのカテゴリ',''),...cats.map(c=>new Option(c,c)));$('filter').value=cats.includes(current)?current:'';
 $('categories').replaceChildren(...cats.filter(c=>c!=='未分類').map(c=>{const o=document.createElement('option');o.value=c;return o}));
 const q=$('search').value.trim().toLocaleLowerCase(),visible=notes.filter(n=>(!$('filter').value||(n.category||'未分類')===$('filter').value)&&(!q||(n.title+' '+n.memo).toLocaleLowerCase().includes(q))).sort((a,b)=>b.updated-a.updated);
 $('list').replaceChildren();if(!visible.length){$('list').append(el('div','panel empty',notes.length?'該当するネタがありません':'まだネタがありません。上のフォームから追加しましょう。'));return}
 for(const n of visible){const card=el('article','card'),head=el('button','note-head');head.type='button';head.setAttribute('aria-expanded',String(opened===n.id));const label=el('span');label.append(el('span','badge',n.category||'未分類'),el('strong','',n.title));head.append(label,el('span','',opened===n.id?'−':'＋'));head.onclick=()=>{opened=opened===n.id?null:n.id;render()};card.append(head);
  if(opened===n.id){card.append(el('p','muted',new Date(n.updated).toLocaleString('ja-JP')),el('div','body',n.memo));const actions=el('div','row');actions.style.marginTop='14px';const edit=el('button','','編集');edit.onclick=()=>{editing=n.id;$('title').value=n.title;$('category').value=n.category||'';$('memo').value=n.memo;$('formTitle').textContent='ネタを編集';$('cancel').hidden=false;window.scrollTo({top:0,behavior:'smooth'});$('title').focus()};const del=el('button','danger','削除');del.onclick=async()=>{if(!confirm('このネタを削除しますか？'))return;try{await api('/api/notes/'+encodeURIComponent(n.id),{method:'DELETE'});notes=notes.filter(x=>x.id!==n.id);if(editing===n.id)reset();opened=null;render()}catch(e){alert(e.message)}};actions.append(edit,del);card.append(actions);
   const chat=el('div','chat');chat.append(el('h2','','AIに相談'));const select=el('select');[['面白くする','この話を人に話すときに面白くなる構成、具体的な言い回し、オチを提案してください。'],['アイデアを広げる','このメモから派生する新しいアイデアを3つ提案してください。'],['自由に質問','']].forEach(([name,prompt])=>select.add(new Option(name,prompt)));const question=el('textarea');question.placeholder='AIへの追加の質問（自由に入力）';question.style.minHeight='75px';const ask=el('button','primary','AIに相談する'),status=el('p','status',''),reply=el('div','reply');reply.hidden=true;ask.onclick=async()=>{const prompt=(select.value+' '+question.value).trim();if(!prompt){status.textContent='質問を入力してください。';return}ask.disabled=true;status.textContent='考えています…';reply.hidden=true;try{const data=await api('/api/advice',{method:'POST',body:JSON.stringify({title:n.title,memo:n.memo,category:n.category||'未分類',question:prompt})});reply.textContent=data.answer;reply.hidden=false;status.textContent=''}catch(e){status.textContent=e.message}finally{ask.disabled=false}};chat.append(select,question,ask,status,reply);card.append(chat)}$('list').append(card)}
}
$('form').onsubmit=async e=>{e.preventDefault();const title=$('title').value.trim(),memo=$('memo').value.trim(),category=$('category').value.trim();if(!title||!memo)return;const payload={id:editing||crypto.randomUUID(),title,memo,category,updated:Date.now()};try{const saved=await api('/api/notes',{method:'POST',body:JSON.stringify(payload)});const i=notes.findIndex(n=>n.id===saved.id);if(i>=0)notes[i]=saved;else notes.push(saved);opened=saved.id;reset();render()}catch(err){alert(err.message)}};
$('cancel').onclick=reset;$('search').oninput=render;$('filter').onchange=render;
async function start(){try{let local=[];try{const parsed=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(parsed))local=parsed}catch{}const data=await api('/api/notes'+(local.length?'?migrate=1':''),local.length?{method:'POST',body:JSON.stringify({notes:local})}:{});notes=data.notes;localStorage.removeItem(KEY);render()}catch(e){$('list').replaceChildren(el('div','panel empty','メモを読み込めませんでした：'+e.message))}}
start();
